"""add table message_status

Revision ID: 189ad96f3a2e
Revises: 82da6048188d
Create Date: 2024-11-16 11:57:01.876096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189ad96f3a2e'
down_revision: Union[str, None] = '82da6048188d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_statuses',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_statuses_message_id', 'message_statuses', ['message_id'], unique=False)
    op.create_index('ix_message_statuses_message_user', 'message_statuses', ['message_id', 'user_id'], unique=False)
    op.create_index('ix_message_statuses_user_id', 'message_statuses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_statuses_user_id', table_name='message_statuses')
    op.drop_index('ix_message_statuses_message_user', table_name='message_statuses')
    op.drop_index('ix_message_statuses_message_id', table_name='message_statuses')
    op.drop_table('message_statuses')
    # ### end Alembic commands ###
