"""update comments table

Revision ID: 2d205558c65c
Revises: 189ad96f3a2e
Create Date: 2024-11-17 15:58:25.012303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d205558c65c'
down_revision: Union[str, None] = '189ad96f3a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('parent_id', sa.String(length=50), nullable=True))
    op.create_index('ix_comments_parent_id', 'comments', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['comment_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index('ix_comments_parent_id', table_name='comments')
    op.drop_column('comments', 'parent_id')
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
