"""Add notification, device_token table

Revision ID: 46b49df43470
Revises: f3d3debbd54a
Create Date: 2024-12-08 17:32:41.736709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b49df43470'
down_revision: Union[str, None] = 'f3d3debbd54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='unique_active_device_token', sqlite_on_conflict='REPLACE')
    )
    op.create_index('ix_device_tokens_device_id', 'device_tokens', ['device_id'], unique=False)
    op.create_index('ix_device_tokens_is_active', 'device_tokens', ['is_active'], unique=False)
    op.create_index('ix_device_tokens_user_id', 'device_tokens', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('FOLLOW', 'LIKE', 'COMMENT', 'MESSAGE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_sender_id', 'notifications', ['sender_id'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('notification_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'recipient_id', name='unique_notification_recipient')
    )
    op.create_index('ix_notification_recipients_is_read', 'notification_recipients', ['is_read'], unique=False)
    op.create_index('ix_notification_recipients_notification_id', 'notification_recipients', ['notification_id'], unique=False)
    op.create_index('ix_notification_recipients_recipient_id', 'notification_recipients', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_recipients_recipient_id', table_name='notification_recipients')
    op.drop_index('ix_notification_recipients_notification_id', table_name='notification_recipients')
    op.drop_index('ix_notification_recipients_is_read', table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index('ix_notifications_sender_id', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_device_tokens_user_id', table_name='device_tokens')
    op.drop_index('ix_device_tokens_is_active', table_name='device_tokens')
    op.drop_index('ix_device_tokens_device_id', table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
