"""Update device token constraints

Revision ID: 53316c32c9e5
Revises: 46b49df43470
Create Date: 2024-12-09 03:43:15.075673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53316c32c9e5'
down_revision: Union[str, None] = '46b49df43470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_active_device_token', 'device_tokens', type_='unique')
    op.create_unique_constraint('unique_active_device_token', 'device_tokens', ['device_id', 'is_active'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_active_device_token', 'device_tokens', type_='unique')
    op.create_unique_constraint('unique_active_device_token', 'device_tokens', ['device_id'])
    # ### end Alembic commands ###
