"""Update notification type to string

Revision ID: ac42f530cc98
Revises: 89a4dbaaec43
Create Date: 2024-12-09 04:11:51.726704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac42f530cc98'
down_revision: Union[str, None] = '89a4dbaaec43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('FOLLOW', 'LIKE', 'COMMENT', 'MESSAGE', 'SYSTEM', name='notificationtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('FOLLOW', 'LIKE', 'COMMENT', 'MESSAGE', 'SYSTEM', name='notificationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
