"""add is_admin column on user table

Revision ID: acac199fa75a
Revises: ac42f530cc98
Create Date: 2025-01-10 04:03:46.385140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acac199fa75a'
down_revision: Union[str, None] = 'ac42f530cc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index('ix_users_is_admin', 'users', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_is_admin', table_name='users')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
