"""Add cascade missing

Revision ID: f3d3debbd54a
Revises: 2d205558c65c
Create Date: 2024-12-06 05:09:24.066749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d3debbd54a'
down_revision: Union[str, None] = '2d205558c65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_creator_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['creator_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_creator_id_fkey', 'conversations', 'users', ['creator_id'], ['user_id'])
    # ### end Alembic commands ###
