"""add report table

Revision ID: fcd9984bfd9c
Revises: 97ff74c0842a
Create Date: 2025-01-13 13:46:32.275111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd9984bfd9c'
down_revision: Union[str, None] = '97ff74c0842a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('reporter_id', sa.String(length=50), nullable=True),
    sa.Column('reported_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('POST', 'COMMENT', name='reporttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'REJECTED', name='reportstatus'), nullable=True),
    sa.Column('content_id', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['reported_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('ix_reports_reported_id', 'reports', ['reported_id'], unique=False)
    op.create_index('ix_reports_reporter_id', 'reports', ['reporter_id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_type', 'reports', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_type', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_reporter_id', table_name='reports')
    op.drop_index('ix_reports_reported_id', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
